### ISSUE TITLE
DateUtils from Android framemork

### ISSUE THREAD

**Issue by remcomokveld** [blundell/YouTubeTimeStamps#2]
I also posted a comment on your blog post, but it seems to have disappeared, but I would like to know if you also looked at the DateUtils class from the Android framework, it seems to me that it does almost the same as this. Albeit maybe a bit less flexible. Or did you have any issues with it?

**Comment by blundell** [comment]
Sorry blog has comments moderation :-) haven't checked them yet.

You're referring to:

http://developer.android.com/reference/android/text/format/DateUtils.html#getRelativeTimeSpanString(long, long, long, int)

Yes my solution is more flexible. I.e. if within 1 minute (which could be 15mins say) then it says "Just Now" instead of the time. The framework cannot do this.

Further you can then modify all of them to be different i.e. not show any actual numbers.

It also shows how the voodoo of a method like this works in the SDK and so means you can do it yourself :-)

Lastly you don't need a `Context` to use the methods presented here :-)
